name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Install mobile deps
        working-directory: mobile
        run: npm ci

      - name: Lint presence
        run: |
          node -v
          npm -v

